### ISSUE TITLE
Some wrong yomigana/hyouki entries

### ISSUE THREAD

**Issue by ghost** [neologd/mecab-ipadic-neologd#12]
// hyouki
mecab-user-dict-seed.20160222.csv:387971: ウグイスタケ,1288,1288,-1686,名詞,固有名詞,一般,_,_,_,鶯〓,ウグイスタケ,ウグイスタケ
mecab-user-dict-seed.20160222.csv:388991: ウチダヒャッケン,1288,1288,-5999,名詞,固有名詞,一般,_,_,_,内田百〓@6BE1@,ウチダヒャッケン,ウチダヒャッケン
(+87 "〓" entries)

// yomigana
mecab-user-dict-seed.20160222.csv:268129: けけ,1289,1289,7587,名詞,固有名詞,人名,一般,_,_,けけ,ケケヶ,ケケヶ
mecab-user-dict-seed.20160222.csv:274205: ずヾや株式会社,1288,1288,4587,名詞,固有名詞,一般,_,_,*,ずヾや株式会社,ズヾヤカブシキガイシャ,ズヾヤカブシキガイシャ

"ヶ" and "ヾ" are not good for Japanese yomigana.

**Comment by neologd** [comment]
Thank you very much for your comment.

I added a process to deleted an entry which has '〓' character from a seed dictionary.

And I added a process to replace a "ODORIJI(in Japanese, 踊り字)" with a kana character.

As the result, I solved this issue on a seed dictionary of next release. 

Thank you very much.
