### ISSUE TITLE
Make capable to install mecab-ipadic-NEologd to an user directory without sudo privileges

### ISSUE THREAD

**Issue by overlast** [neologd/mecab-ipadic-neologd#21]
Currently, I should set "--asuser option" to install the mecab-ipadic-NEologd to an user directory without sudo privileges.
But I would like mecab-ipadic-NEologd to detect whether sudo privileges are required.

So I will implement following features
- A process to compare an uid of a current user and an uid of target directory
- assudo option
  - It's required when I want to install using sudoer privileges

**Comment by neologd** [comment]
This issue was solved by following P-R.
https://github.com/neologd/mecab-ipadic-neologd/pull/25
