### ISSUE TITLE
mecab-ipadic-NEologd won't be updated when running the installer with the full path

### ISSUE THREAD

**Issue by matsulib** [neologd/mecab-ipadic-neologd#23]
I ran a cron job with the full path installer and -n option, like,

```
00 03 * * 2 /opt/mecab/mecab-ipadic-neologd/bin/install-mecab-ipadic-neologd -n -y
```

Then the following errors occurred.

```
fatal: Not a git repository (or any of the parent directories): .git
fatal: 'origin' does not appear to be a git repository
fatal: Could not read from remote repository.
```

This occurred in the following code because the current directory was not a git repository.

```
if [ `git log refs/heads/master --pretty=%H | head -1` = `git ls-remote origin -h refs/heads/master |cut -f1` ]; then
    echo "$ECHO_PREFIX mecab-ipadic-NEologd is already up-to-date"
```

In this case, the condition is always true because both of the results are empty.
Therefore, the message "mecab-ipadic-NEologd is already up-to-date" is always displayed.

**Comment by neologd** [comment]
Thank you very much !!
I am surprised that such a bug is still remaining.
I'm reviewing your P-R now.

**Comment by neologd** [comment]
I merged your P-R.
Thank you for your nice commitment :)
