### ISSUE TITLE
出力エンコーディングの指定

### ISSUE THREAD

**Issue by sky-y** [neologd/mecab-ipadic-neologd#3]
Windows環境(C#, NMeCaB)で使用しているのですが、出力エンコーディングがUTF8なので少し手を加えないと使用できません。

コンパイル環境はUnixで当面良いので、出力エンコーディングをインストーラのオプションで指定できるようにしてもらえると助かります。

参考(自著ブログ): [mecab-ipadic-neologdをNMeCab用にshift-jisでコンパイルした - 雲行きそらゆきココロイキ](http://sky-y.hatenablog.jp/entry/2015/07/08/190456)

**Comment by neologd** [comment]
ご報告どうもありがとうございます。

ご報告いただいた不具合は、以下から取得可能な最新版のNMeCabと同じバージョンで起きる不具合でしょうか。(2015-07-08時点ではv0.07のようです)

http://osdn.jp/projects/nmecab/

NMeCabはご報告頂きました不具合に以下のコミットで対応なさったようです。

http://osdn.jp/projects/nmecab/scm/git/NMeCab/commits/86e8a0ecc6943322303429f842944341537829dd

もしもお手元の環境で最新版のNMeCabを使った際に、
ご報告頂きました不具合が解消されていることが確認できた場合は、
以下のパッケージを管理している方に、最新版のパッケージを作成をお願いして、
さらにnugetにアップしていただくのは如何でしょうか。

https://www.nuget.org/packages/NMeCab/

UTF-8 から Shift_JIS など他の文字コードへの変換はいろいろと考慮することが多いです。

取り組むべき課題が現状ではとても多いため、
UTF-8 以外の文字コードに正常な形で対応するためのリソースを、
いまのところ我々は確保できません。

最新版 NMeCab が UTF-8 な辞書を利用できるということでしたら、nuget 側で対処して頂ければと思います。

ご検証いただき、ご返答いただけますでしょうか。

よろしくお願いいたします。

**Comment by neologd** [comment]
この Issue なのですが、以下の3点の観点から緊急度が極めて低い Issue であると一旦判断し、close させていただきます。
- UTF-8 から Shift_JIS への変換が最新の NMeCab には不要である
- こちらはすでに根本的な解決策を提案した
- こちらが出した結論に対するレスポンスが長期間いただけていない

同じ問題が、再びどうしても解決できない問題として現れた時に、再考させていただきます。
