### ISSUE TITLE
What is the correct way to customize the pos-id.def file in mecab-ipadic-neologd?

### ISSUE THREAD

**Issue by frankang** [neologd/mecab-ipadic-neologd#31]
Hi,
I'm trying to modify the pos-id.def coming with the neologd dictionary. But after changing that file, whether I execute 
`sudo ./mecab-dict-index -f UTF8 -t UTF8 -d /usr/lib/mecab/dic/mecab-ipadic-neologd`
or execute
`sudo ./mecab-dict-index -f UTF8 -t UTF8 -d .../build/mecab-ipadic-2.7.0-20070801-neologd-20170710>`,
I would get the error "

> dictionary_compiler.cpp(133) [dic.size()] no dictionaries are specified
 or 
> char_property.cpp(236) [unk.find(it->first) != unk.end()] category [ALPHA] is undefined in ...../mecab-ipadic-neologd/build/mecab-ipadic-2.7.0-20070801-neologd-20170710/unk.def

respectively.

So could anyone tell me the correct way to compile the new pos-id.def for the neglogd dictionary? Any hint is appreciated. Thanks.

**Comment by neologd** [comment]
Have you solved this issue?

Our answer is only one.
mecabipadic-NEologd has already over-customized mecab-ipadic.
Therefore, if this is your first pos-id.def editing, we recommend you to customize mecab-ipadic for practice first.

http://taku910.github.io/mecab/posid.html

After that, you will be able to resolve the doubt 😊

Please continue to use NEologd. Thank you very much ✨
