### ISSUE TITLE
how to set in mecabrc file?

### ISSUE THREAD

**Issue by zukakosan** [neologd/mecab-ipadic-neologd#33]
I want to use this dictionary with ipadic on python. 
What to write in mecabrc file?

**Comment by neologd** [comment]
To use mecab-ipadic-NEologd as a system dictionary, you can use it by specifying the install directory of mecab-ipadic-NEologd with the -d option.
Please install mecab-ipadic-NEologd and follow the README of mecab-ipadic-NEologd.

When using mecab-ipadic-NEologd as an user dictionary, please write the absolute path of the user dictionary to the 'userdic' field of the mecabrc.

Execute a following command to get the user dictionary.

    ./bin/install-mecab-unidic-neologd --create_user_dic

Details are described in the following official manual.

http://taku910.github.io/mecab/dic.html

Thank you for your question. Please continue to use NEologd ✨
