### ISSUE TITLE
How to produce mecab-user-dict-seed.YYYYMMDD.csv.xz?

### ISSUE THREAD

**Issue by tmshn** [neologd/mecab-ipadic-neologd#35]
Hi, I love and appreciate this helpful dictionary!

A quick question: how do you produce seed file `mecab-user-dict-seed.YYYYMMDD.csv.xz`?
I suppose you use some scripts to it, but if so, the scripts are also uploaded to the git repo?

I'm looking for the way to build a bit customized-version of the dic.

Thanks in advance!

**Comment by neologd** [comment]
Thank you for your comment 😊

We don't plan to release the seed dictionary construction system as OSS.
On the other hand, we plan to continue updating the dictionary for more than 10 years.

If you have useful linguistic resources and it's useful for many people in the world to merge it with NEologd, we can work with you to produce results.

When you customize mecab-ipadic-NEologd, let's move to the directory with build date in build directory first.
Then edit any CSV file in that directory and then execute the make command.
You will be able to create your own system dictionary.

Please continue to use NEologd ✨
Thank you very much.
