### ISSUE TITLE
neologdを使ってみて思ったのですが

### ISSUE THREAD

**Issue by kondoudesu45** [neologd/mecab-ipadic-neologd#37]
こんにちわ。
使わせて頂いてありがとうございます。
さて、数字やローマ字、記号の混じったものは名詞・固有名詞となっています。
ipadicでは数要素であることがfeatureで分かります。
同じように数字などの混じった名詞・固有名詞に、例えば度量衡などの要素を加えて頂けませんか？
良い案があれば、その他の方法でも良いです。
単体で￥は記号、その他の%、kg、cm、Ⅼ（リットルと読めない）は名詞です。
例えば、4カ月　  名詞、固有名詞、一般、度量衡
　　　　5つ　  　名詞、一般、　　　　、度量衡
　　　　A型　  　名詞、固有名詞、一般、度量衡
　　　　35℃　　名詞、固有名詞、一般、度量衡
　　　　70％　　名詞、固有名詞、一般、度量衡
　　　　65kg　　名詞、固有名詞、一般、度量衡
　　　　180cm　 名詞、固有名詞、一般、度量衡
　　　　500m3    　※これは分割されてしまいます。
　　　　8個（ケ）  ※これは分割されてしまいます。
                                5l※リットルと読めるが、分割されてしまいます。

**Comment by neologd** [comment]
Thank you for your feedback.

NEologd knows what kind of expression is the quantity expression on our backend.
However, it was not reasonable to embed the expression you requested, especially as a MeCab's dictionary.

As an alternative that can be done right now, we suggest that you capture the results of a normal IPADIC analysis in parallel and process the results using mecab-ipadic-NEologd.

We will continue to consider whether there is a better plan.
Thank you.
