### ISSUE TITLE
 README.md のBibtexについて

### ISSUE THREAD

**Issue by ghost** [neologd/mecab-ipadic-neologd#38]
2017年度の言語処理学会と，2016年度の情報処理学会の論文の author についてですが，
橋本泰一さんの名前が ```Taiichi Hashimoro``` とタイポしているかと思います．
```Taiichi Hashimoto``` が正しいかと．

**Comment by neologd** [comment]
Thank you very much for finding incorrect strings.
I fixed them. Thanks !!
