### ISSUE TITLE
installer reports error

### ISSUE THREAD

**Issue by hidekuro** [neologd/mecab-ipadic-neologd#4]
installer reports `fatal: ambiguous argument '...refs/heads/master^': unknown revision or path not in the working tree.`

system env:

```
~% $SHELL '--version'
zsh 5.0.2 (x86_64-pc-linux-gnu)

~% git --version
git version 2.5.0
```

detail logs:

```
....

fatal: ambiguous argument '...refs/heads/master^': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
[install-mecab-ipadic-neologd] : Get the newest updated information using git
./bin/install-mecab-ipadic-neologd: line 199: [: =: unary operator expected
HEAD is now at f987dff Fix typo

[install-mecab-ipadic-neologd] : mecab-ipadic-neologd will be install to /usr/lib64/mecab/dic/mecab-ipadic-neologd

....
```

**Comment by neologd** [comment]
Thank you for your report about bin/install-mecab-ipadic-neologd.

I am sorry for the lack of confirmation.
I fixed the code about checking a update information on remote repository of mecab-ipadic-neologd and confirmed the result of my correction.

Please check the following commit log.

https://github.com/neologd/mecab-ipadic-neologd/commit/fb388c9ba92dca62c28e8f63297dd9cbeb9fee54

Thank you very much !!
