### ISSUE TITLE
すもももももももものうち

### ISSUE THREAD

**Issue by myamanishi3** [neologd/mecab-ipadic-neologd#41]
辞書を自分で鍛えるのが面倒なので、新し目の辞書を探していてmecab-ipadic-neologdに行き当たりました。なるほど今まで細切れになっていたものが一語として認識され調子良さそうです。しかしながら、ひとつこまったことが。「すもももももももものうち」を解析すると、一般名詞「すもももももももものうち」と解析されてしまいます。

これは辞書をmakeする過程でなにか足りなかったからなのでしょうか？それとも、こういう仕様なのでしょうか？

同じようにmecab-unidic-neologdの方も一般名詞となってしまうことを確認しております。

**Comment by neologd** [comment]
Hello. Thanks for your comment 😊

> Is this true spec of me cab-ipadic-NEologd ?

Yes. That's right.

We think that the word "すもももももももものうち" is like an idiomatic phrase.
As an editing policy of NEologd to date, we have made idioms as "one word" as possible.

In the application of NEologd that we assumed so far, there were many uses for erasing "すもも" when "すもももももももものうち" can be extracting than the use for extracting "すもも"  from "すもももももももものうち".

If we want to extract "すもも"  from "すもももももももものうち", we also use ordinary IPADIC or UniDic.

Is the problem solved?

**Comment by myamanishi3** [comment]
Thank you very much for replying.

I understand the fact, and agree with it.

Though "すもももももももものうち" is listed as the first example of MeCab usage, "mecab" did not give wakati gaki.  That was why I thought my dictionary could be broken.

I do not intend to have wakati gaki of "すもももももももものうち".  In the case, I will use the original ipadic or unidic.
