### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by Gasol** [neologd/mecab-ipadic-neologd#45]
## Motivation
I hope people can install latest updated package with fresh data. 

I has packaged version 0.0.5 of mecab-ipadic-neologd which released on 2016-05-02 for Debian and derived distribution like Ubuntu, also release the packaging file on both [Launchpad PPA](https://launchpad.net/~gasol-wu/+archive/ubuntu/xenial) and [Bintray](https://bintray.com/gasolwu/deb/mecab-ipadic-neologd), So people can easily install by command `apt-get install mecab-ipadic-neologd`.

## Goal
- Release new version for updated data

**Comment by neologd** [comment]
Thank you for your opinion.
And I appreciate that you were releasing the packages for various distributions.

I released v0.0.6 using latest version of seed data.
Thank you very much for your cooperation.

**Comment by Gasol** [comment]
Package for Debian 9 is published on [mecab-ipadic-neologd_0.0.6-1bintray1~stretch_all.deb](https://bintray.com/gasolwu/deb/mecab-ipadic-neologd/0.0.6-1bintray1~stretch), I can help to package older distribution If someone needs.
