### ISSUE TITLE
Missing Japanese names

### ISSUE THREAD

**Issue by utuhiro78** [neologd/mecab-ipadic-neologd#49]
These names are missing in mecab-user-dict-seed.20181112.csv and mecab-ipadic-2.7.0-20070801.
I think they are famous/common names.

サンペイ	三瓶
ソウシゲル	宗茂
タケユタカ	武豊
ユウト	勇人
リンカ	梨花

**Comment by neologd** [comment]
Thank you for your request.

Now, we try to solve this type of issue.
Please wait for a few months.

Thank you.

**Comment by neologd** [comment]
Hi, sorry for the long time to resolve.

These cases you reported in this issue has been resolved.
In addition, we will improve the same kind of bugs soon.

Please give us useful reports in the future.
Thank you.

    $ mecab -d /usr/lib64/mecab/dic/mecab-ipadic-neologd/
    三瓶
    三瓶    名詞,固有名詞,人名,一般,*,*,三瓶,サンペイ,サンペイ
    EOS
    宗茂
    宗茂    名詞,固有名詞,人名,一般,*,*,宗茂,ソウシゲル,ソウシゲル
    EOS
    武豊
    武豊    名詞,固有名詞,人名,一般,*,*,武豊,タケユタカ,タケユタカ
    EOS
    梨花
    梨花    名詞,固有名詞,人名,一般,*,*,梨花,リンカ,リンカ
    EOS
    $ mecab -d /usr/lib64/mecab/dic/mecab-ipadic-neologd/ -N3
    勇人
    勇人    名詞,固有名詞,人名,一般,*,*,勇人,ユウト,ユウト
    EOS
    勇人    名詞,固有名詞,人名,一般,*,*,勇人,ハヤト,ハヤト
    EOS
    勇人    名詞,固有名詞,一般,*,*,*,勇人,ユウト,ユウト
