### ISSUE TITLE
normalize_neologd.pyの間違い？

### ISSUE THREAD

**Issue by arosh** [neologd/mecab-ipadic-neologd#5]
WikiのRegexp.jaのページに記載されているnormalize_neologd.pyですが，

``` python
s = unicode_normalize('０−９Ａ-Ｚａ-ｚ｡-ﾟ', s)
```

の部分の０と９の間がHYPHEN-MINUSではなくMINUS SIGNになっています．

「１０日」を正規化すると「10日」のようになると思うのですが，現在のソースコードでは「１0日」のようになってしまいます (Python 2.7.9で確認)．

以下の変更をマージしていただけませんか？

https://github.com/arosh/mecab-ipadic-neologd-wiki/commit/0e5534dd09d936459916502e0126056f8372812e

(Wikiに対するPull Requestの方法が分からなかったので，Issueで質問させていただきました）

**Comment by neologd** [comment]
ご報告どうもありがとうございます。

不具合の内容を確認し Wiki を修正しました。
また、ご提案頂いたテストよりも多めにテストを足しました。
さらに、Ruby のコードにも不具合を確認しましたので修正しました。

以下のhistory内で変更を確認できます。

https://github.com/neologd/mecab-ipadic-neologd/wiki/Regexp.ja/_history

とても助かりました。どうもありがとうございました。
