### ISSUE TITLE
Download common-nouns.csv of specific date

### ISSUE THREAD

**Issue by Bilguunkhan** [neologd/mecab-ipadic-neologd#50]
## Motivation
- Extract newly added nouns to the dictionary using the current common-nouns.csv and the last year's common-nouns.csv
## Goal
- Download latest common-nouns.csv and last year'S common-nouns.csv.
- Is there any way we could download common-nouns.csv of specific date? 
I have looked into the /seeds/ directory but it seems that there is only 2017/02's common-nouns.csv. 

With best regards

**Comment by neologd** [comment]
Thank you for your request.
And we're sorry for our late reaction.

In conclusion, there is no way to download common-nouns.csv on a particular day.

The repository related to NEologd has a large amount of transfer per unit time.
Therefore, if we keep releasing old data, our personal expenses will increase too much and you will not be able to maintain a free dictionary offering.

It will be difficult to obtain common-nouns.csv for a specific date for free.
On the other hand, we would like to be able to download a specific version of dictionary data for business purposes.

We are going to release the service for that during the year.
Please wait for that time.
