### ISSUE TITLE
Cannot Install mecab-python3 (unable to execute swig: no such file in directory)

### ISSUE THREAD

**Issue by nburkhalter** [neologd/mecab-ipadic-neologd#51]
## Motivation

Hello,
I've successfully installed MeCab, mecab-ipadic, and the neological dictionary. However, I cannot install mecab-python3 to get MeCab talking with Python. Each time I've tried, I receive the following error:

    unable to execute 'swig': No such file or directory
    error: command 'swig' failed with exit status 1

From what I've gathered looking into the issue on Google, it seems to be an issue that resulted from the most recent update. Was wondering if there was a temporary fix until the issue gets resolved?

I ran across this online:

https://qiita.com/siraasagi/items/e07e0b271cb7cd679a70

 but as I'm using a Mac, I cannot run apt in the command line. Brew also does not recognize the formulae when I substitute it with apt-get. Any help would be much appreciated!

Thanks for your time!

## Goal
Goal is to use MeCab with Python to tokenize some Japanese text for NLP purposes.

**Comment by chezou** [comment]
Recently, mecab-python3 requires swig, Use `brew install swig` to install it.
see also 
https://brewformulas.org/swig

**Comment by neologd** [comment]
Thank you very much @chezou san.

This issue isn't ours.

However, I tried to install python-mecab3 module with Python3.7.2 on macOS 10.13.6.
The following is the installation procedure.

    $ pip install mecab-python3
    Collecting mecab-python3
     Downloading https://files.pythonhosted.org/packages/ac/48/295efe525df40cbc2173748eb869290e81a57e835bc41f6d3834fc5dad5f/mecab-python3-0.996.1.tar.gz
      Installing collected packages: mecab-python3
     Running setup.py install for mecab-python3 ... error
       Complete output from command /Users/overlast/local/python-3.7.2/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/wk/vrj6jk1s6dx1_t5_kxllkf640000gp/T/pip-install-2jet6bd8/mecab-python3/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/wk/vrj6jk1s6dx1_t5_kxllkf640000gp/T/pip-record-0ijuqygb/install-record.txt --single-version-externally-managed --compile:
       running install
       running build
       running build_py
       running build_ext
       building '_MeCab' extension
       swigging MeCab.i to MeCab_wrap.cpp
       swig -python -shadow -c++ -I/usr/local/Cellar/mecab/0.996/include -o MeCab_wrap.cpp MeCab.i
       unable to execute 'swig': No such file or directory
       error: command 'swig' failed with exit status 1
   
       ----------------------------------------
      Command "/Users/overlast/local/python-3.7.2/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/wk/vrj6jk1s6dx1_t5_kxllkf640000gp/T/pip-install-2jet6bd8/mecab-python3/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/wk/vrj6jk1s6dx1_t5_kxllkf640000gp/T/pip-record-0ijuqygb/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/wk/vrj6jk1s6dx1_t5_kxllkf640000gp/T/pip-install-2jet6bd8/mecab-python3/
    $ brew upgrade
    $ brew install swig
    Updating Homebrew...
    ==> Installing dependencies for swig: pcre
    ==> Installing swig dependency: pcre
    ==> Downloading https://homebrew.bintray.com/bottles/pcre-8.42.high_sierra.bottle.tar.gz
    ########################################################################       100.0%
    ==> Pouring pcre-8.42.high_sierra.bottle.tar.gz
    🍺  /usr/local/Cellar/pcre/8.42: 204 files, 5.3MB
    ==> Installing swig
    ==> Downloading https://homebrew.bintray.com/bottles/swig-3.0.12.high_sierra.bottle.tar.gz
    ######################################################################## 100.0%
    ==> Pouring swig-3.0.12.high_sierra.bottle.tar.gz
    🍺  /usr/local/Cellar/swig/3.0.12: 755 files, 5.5MB
    $ pip install mecab-python3
    Collecting mecab-python3
      Using cached https://files.pythonhosted.org/packages/ac/48/295efe525df40cbc2173748eb869290e81a57e835bc41f6d3834fc5dad5f/mecab-python3-0.996.1.tar.gz
    Installing collected packages: mecab-python3
      Running setup.py install for mecab-python3 ... done
    Successfully installed mecab-python3-0.996.1


I think this issue is solved. So, I close this issue. Thanks.
