### ISSUE TITLE
Download failed in China

### ISSUE THREAD

**Issue by kan-bayashi** [neologd/mecab-ipadic-neologd#52]
Hi. Thank you for sharing a great dictionary!
Currently, we are using your dict for Japanese text-to-speech system in [our project](https://github.com/espnet/espnet).

The users from China reported the failure of downloading due to the block of google drive service.
https://github.com/espnet/espnet/issues/606
Is there any plan to provide another download source for the installation?

**Comment by neologd** [comment]
Thank you for your opinion.
The primary download source of IPADIC has been changed from Google to OSDN.
Please let me know when you can't download IPADIC from OSDN.
In this case, we will consider other ways.
Thank you very much.
