### ISSUE TITLE
「世界の秘密」

### ISSUE THREAD

**Issue by ghost** [neologd/mecab-ipadic-neologd#58]
Hello, 
This dictionary is very good!
I use it every day.
Thank you so much.

By the way, a phrase "世界の秘密" is analyzed a token of this dictionary.
The phrase is a quiz TV program name.
But, that TV program ended only five months.
I think that the phrase should be analyzed "世界" + "の" + "秘密".

**Comment by neologd** [comment]
Thank you for nice feedback.
The latest version resolves this issue.
