### ISSUE TITLE
'三重県' and '群馬県' are parsed as name of person

### ISSUE THREAD

**Issue by t-chov** [neologd/mecab-ipadic-neologd#59]
Both `三重県` and `群馬県` are name of prefecture. Other prefectures are analyzed as `名詞-固有名詞-地域-一般` correctly.

But these prefectures are analyzed as `名詞-固有名詞-人名-一般` and I find these are in seed file. There are no famous persons named `三重県` nor `群馬県` as I searched.

I think both of words should be analyzed as `名詞-固有名詞-地域-一般`.

### Result of analysis

```
茨城県  名詞,固有名詞,地域,一般,*,*,茨城県,イバラキケン,イバラキケン
栃木県  名詞,固有名詞,地域,一般,*,*,栃木県,トチギケン,トチギケン
群馬県  名詞,固有名詞,人名,一般,*,*,群馬県,グンマケン,グンマケン
愛知県  名詞,固有名詞,地域,一般,*,*,愛知県,アイチケン,アイチケン
岐阜県  名詞,固有名詞,地域,一般,*,*,岐阜県,ギフケン,ギフケン
三重県  名詞,固有名詞,人名,一般,*,*,三重県,ミエケン,ミエケン
```

### Seed file

```
./build/mecab-ipadic-2.7.0-20070801-neologd-20190812/mecab-user-dict-seed.20190812.csv:三重県,1289,1289,-2894,名詞,固有名詞,人名,一般,*,*,三重県,ミエケン,ミエケン
./build/mecab-ipadic-2.7.0-20070801-neologd-20190812/mecab-user-dict-seed.20190812.csv:群馬県,1289,1289,1138,名詞,固有名詞,人名,一般,*,*,群馬県,グンマケン,グンマケン
```

**Comment by neologd** [comment]
Thank you for your feedback.
This type of error has been corrected.

    $mecab -d /usr/lib64/mecab/dic/mecab-ipadic-neologd/
    三重県と群馬県はどちらも人名ではないです。
    三重県  名詞,固有名詞,地域,一般,*,*,三重県,ミエケン,ミエケン
    と      助詞,並立助詞,*,*,*,*,と,ト,ト
    群馬県  名詞,固有名詞,地域,一般,*,*,群馬県,グンマケン,グンマケン
    は      助詞,係助詞,*,*,*,*,は,ハ,ワ
    どちら  名詞,代名詞,一般,*,*,*,どちら,ドチラ,ドチラ
    も      助詞,係助詞,*,*,*,*,も,モ,モ
    人名    名詞,一般,*,*,*,*,人名,ジンメイ,ジンメイ
    で      助詞,格助詞,一般,*,*,*,で,デ,デ
    は      助詞,係助詞,*,*,*,*,は,ハ,ワ
    ない    助動詞,*,*,*,特殊・ナイ,基本形,ない,ナイ,ナイ
    です    助動詞,*,*,*,特殊・デス,基本形,です,デス,デス
    。      記号,句点,*,*,*,*,。,。,。
    EOS

Thank you.
