### ISSUE TITLE
組織名「日生協」/「日本生活協同組合連合会」

### ISSUE THREAD

**Issue by knok** [neologd/mecab-ipadic-neologd#6]
単語の追加に関する要望があります。
いわゆる「生協」(COOP)の略称「日生協」と正式名称の「日本生活協同組合連合会」を追加してほしいです。

現状、人名の姓として「日生」のみが辞書に存在するため、「日生協」を処理すると
「日生」と「協」に分割されてしまいます。

パッチの形にする良い方法が浮かばなかったので、Issueとして報告します。

**Comment by neologd** [comment]
■ 要約
(例外的に)対応しました。対応の結果は来週月曜日の更新で反映される予定です。

■ ご要望に対するコメント
NEologd の現状の編集方針では、固有の単語を登録するリクエストを基本的に歓迎しないことにしています。パッチをお送り頂いても取り込むことは難しかったと思います。

その理由は、単語追加/編集のリクエストは無限におこなうことができ、一つ一つのリクエストを処理していると全体の開発が滞るからです。

採録している語について極めて重大なエラーなどがございましたら、それに関しましてては Issue を立てていただきたいです。

また、略語に対する対応は別の問題で、私たちは個別の単語に対して任意の略語を設定する対応をする予定が今のところありません。
略語に対する対応も、なるべく自動化しようとしています。

■ NEologd の資源追加に関する方針の一部
他方、大体以下の3条件が揃っている場合は、資源を積極的に取り込むことにしています。
- 現状とある分野(動物とか、顔文字とか、そういうのです)に関する資源がゴッソリと欠けている
- ゴッソリと欠けている資源の専門性がまったく高くない
  - 医学用語とかは避けたい、とかそういうことです
- その資源が他のエントリに与える副作用が極めて少ない

たとえば、過去には「日本の山の名前」などは網羅的なリストを作成して追加しました。

■ 今回行った判断
今回は、消費者団体に関するリストが不足していると判断し、リストを作成することにしました。

■ 今回行った対応
消費者庁が発行した平成23年度の消費者団体名簿から消費者団体に関するリストを作成し、辞書に取り込みました。

http://www.caa.go.jp/region/index10_1.html

結果として、日本生活協同組合連合会以外の消費者団体も網羅する形で採録することになりました。

日本生活協同組合連合会の略語は、作業の過程で瞬間的に追加できるものだったので、例外的に手作業で追加しました。

今後も基本的に自動獲得した略語以外はなるべく追加しない方針です。

以上です。

Issue ありがとうございます。今後もよろしくお願い致します。
