### ISSUE TITLE
Morphological analysis result of "夫婦" is wrong

### ISSUE THREAD

**Issue by ryoasu** [neologd/mecab-ipadic-neologd#65]
## Motivation
I think the morphological analysis result of "夫婦" is wrong.
(build version: `mecab-ipadic-2.7.0-20070801-neologd-20190919`)
```
echo "夫婦" | mecab -d /usr/local/lib/mecab/dic/mecab-ipadic-neologd/
夫婦    名詞,固有名詞,一般,*,*,*,夫婦。,フウフ,フーフ
```

1.  Original (原形) of "夫婦" is `夫婦` instead of `夫婦。`
2. "夫婦" (Type of noun/品詞細分類1) is `一般` instead of `固有名詞`

## Goal
1. Fix original to `夫婦` from `夫婦。`
2. Fix type of noun to `一般`  from `固有名詞`

Could you deal with this issue for me?

**Comment by neologd** [comment]
Thank you for your feedback.
We corrected the issue that you are reported.

    [overlast@]$mecab -d /usr/lib64/mecab/dic/mecab-ipadic-neologd
    夫婦。
    夫婦    名詞,一般,*,*,*,*,夫婦,フウフ,フーフ
    。      記号,句点,*,*,*,*,。,。,。
    EOS

Please use our product in the future.
Thank you.
