### ISSUE TITLE
🏯安土城の読み方はアヅチグスク,アズチグスクであるべきか

### ISSUE THREAD

**Issue by dAu6jARL** [neologd/mecab-ipadic-neologd#66]
found in mecab-user-dict-seed.20191230.csv.xz

```Console
$ mecab -d /usr/local/lib/mecab/dic/mecab-ipadic-neologd
安土城
安土城  名詞,固有名詞,一般,*,*,*,安土城,アヅチグスク,アズチグスク
EOS
```

**Comment by neologd** [comment]
Thank you for your feedback.

This issue is solved after most recent release.

    $mecab -d /usr/lib64/mecab/dic/mecab-ipadic-neologd
    安土城
    安土城  名詞,固有名詞,地域,一般,*,*,安土城,アヅチジョウ,アズチジョー
    EOS

Please use NEologd to achieve great goals in the future.
Thank you !!
