### ISSUE TITLE
Wide "，" is included in 原形

### ISSUE THREAD

**Issue by utuhiro78** [neologd/mecab-ipadic-neologd#67]
```
$ ag アースウィンドアンドファイアー mecab-user-dict-seed.20200123.csv 
151101:Earth Wind & Fire,1288,1288,4131,名詞,固有名詞,一般,*,*,*,Earth，Wind&Fire,アースウィンドアンドファイアー,アースウィンドアンドファイアー
```

I think this is better.
```diff
- Earth，Wind&Fire
+ Earth, Wind&Fire
```

**Comment by neologd** [comment]
We think, your idea is very correct.
This is a fundamental problem with many Japanese morphological analysis dictionaries.

The easiest solution is following 4 steps.

- Step1.  Believe in mecab-ipadic-NEologd
- Step2. Convert "," to "，" before processing
- Step3. Use some morphological analyzer
- Step4. Convert "，" to "," after processing

We'd like to try changing the dictionary delimiter in the future.

In that case, however, compatibility as a dictionary of OSS is sacrificed.
It is also necessary to rebuild the morphological analysis library for the dictionary.

We don't think we can complete the support for the combination of new dictionary using new  delimiters and the custom builded morphological analysis library.

Do you understand a little why we came to the present situation?

Thank you for proposing the problem.
We have the same problem, so we will try to find an effective solution.
