### ISSUE TITLE
A small script to find wrong yomigana entries

### ISSUE THREAD

**Issue by ghost** [neologd/mecab-ipadic-neologd#8]
Hello,

First of all, your mecab-ipadic-neologd is amazing.
Thank you so much!

I wrote a small script and found some wrong yomigana entries.
[find-neologd-error-entries.rb.txt](https://github.com/neologd/mecab-ipadic-neologd/files/89987/find-neologd-error-entries.rb.txt)
[neologd-error-entries.txt](https://github.com/neologd/mecab-ipadic-neologd/files/89988/neologd-error-entries.txt)

$ ruby find-neologd-error-entries.rb mecab-user-dict-seed.20160111.csv
It generates "neologd-error-entries.txt".

e.g.
- 京都市上京区西町,1293,1293,-1319,名詞,固有名詞,地域,一般,_,_,京都市上京区西町,キョウトシカミギョウクニシマチニシマチニシマチニシマチニシマチニシマチニシマチ,キョートシカミギョークニシマチニシマチニシマチニシマチニシマチニシマチニシマチ
- 神津小学校,1288,1288,352,名詞,固有名詞,一般,_,_,*,神津小学校,カミツショウガッコウコウヅショウガッコウ,カミツショーガッコーコーズショウガッコー

I know we can't get yomigana perfectly, but neologd may have some errors in zip code data splitting.

**Comment by neologd** [comment]
Thank you for your feedback.
Also, I apologize for taking several years to respond.

We have gradually achieved a state in which the error you pointed out does not occur.
And we will report that the error disappeared once.

It may happen again, but we can promise that we will improve continuously from now on.
Thank you very much.
