### ISSUE TITLE
Newbie issue with $ mecab -d /usr/local/lib/mecab/dic/mecab-ipadic-neologd/

### ISSUE THREAD

**Issue by hmcgaughey** [neologd/mecab-ipadic-neologd#86]
I'm trying to install the neologd辞書 and am following the instructions in the README.md file. I am able to proceed as far as the code for checking useful command line options:

`./bin/install-mecab-ipadic-neologd -h`

Next, under "How to use mecab-ipadic-NEologd," you explain how to set the path for the custom system dictionary. The code you suggest is

`$ mecab -d /usr/local/lib/mecab/dic/mecab-ipadic-neologd/`

However, when I put this (with modifications for my file structure) into my Mac Terminal (see below), I receive the following error:

`$mecab -d ~/Library/mecab/dic/mecab-ipadic-neologd/`
`param.cpp(69) [ifs] no such file or directory: /Users/hannamcgaughey/Library/mecab/dic/mecab-ipadic-neologd/dicrc`

I can't seem to find that file using my system finder either. Have I done something wrong in the installation?

I look forward to hearing from you!

**Comment by hmcgaughey** [comment]
I have now found the hidden /usr/local/lib/mecab/dic/ folder, but there is no mecab-ipadic-neologd folder in it. Still trying to figure this out...

**Comment by shilik** [comment]
I would suggest you try to install again, if it works it should have something like the picture.
<img width="468" alt="image" src="https://user-images.githubusercontent.com/1404868/230603727-e4e0421e-1bd8-4c2c-8fe8-f7382cc24131.png">

**Comment by hmcgaughey** [comment]
Dear shilik,

Thank you very much for taking the time to answer. I have tried to install again and am still unable to find the folder within /usr/local/lib/mecab/dic/. This is what it looks like in my terminal:

> $ git clone --depth 1 https://github.com/neologd/mecab-ipadic-neologd.git
> Cloning into 'mecab-ipadic-neologd'...
> remote: Enumerating objects: 75, done.
> remote: Counting objects: 100% (75/75), done.
> remote: Compressing objects: 100% (74/74), done.
> remote: Total 75 (delta 5), reused 54 (delta 0), pack-reused 0
> Receiving objects: 100% (75/75), 58.09 MiB | 419.00 KiB/s, done.
> Resolving deltas: 100% (5/5), done.
> $ cd mecab-ipadic-neologd
> $ ./bin/install-mecab-ipadic-neologd -n
> [install-mecab-ipadic-NEologd] : Start..
> [install-mecab-ipadic-NEologd] : Check the existance of libraries
> [install-mecab-ipadic-NEologd] :     find => ok
> [install-mecab-ipadic-NEologd] :     sort => ok
> [install-mecab-ipadic-NEologd] :     head => ok
> [install-mecab-ipadic-NEologd] :     cut => ok
> [install-mecab-ipadic-NEologd] :     egrep => ok
> [install-mecab-ipadic-NEologd] :     mecab => ok
> [install-mecab-ipadic-NEologd] :     mecab-config => ok
> [install-mecab-ipadic-NEologd] :     make => ok
> [install-mecab-ipadic-NEologd] :     curl => ok
> [install-mecab-ipadic-NEologd] :     sed => ok
> [install-mecab-ipadic-NEologd] :     cat => ok
> [install-mecab-ipadic-NEologd] :     diff => ok
> [install-mecab-ipadic-NEologd] :     tar => ok
> [install-mecab-ipadic-NEologd] :     unxz is not found.
> $ echo `mecab-config --dicdir`"/mecab-ipadic-neologd"
> /usr/local/lib/mecab/dic/mecab-ipadic-neologd
> $ mecab -d /usr/local/lib/mecab/dic/mecab-ipadic-neologd/
> param.cpp(69) [ifs] no such file or directory: /usr/local/lib/mecab/dic/mecab-ipadic-neologd/dicrc
> $ echo "8月3日に放送された「中居正広の金曜日のスマイルたちへ」(TBS系)で、1日たった5分でぽっこりおなかを解消す るというダイエット方法を紹介。キンタロー。のダイエットにも密着。" | mecab -d /usr/local/lib/mecab/dic/mecab
> param.cpp(69) [ifs] no such file or directory: /usr/local/lib/mecab/dic/mecab/dicrc

I'm sorry I'm not more of an expert and able to figure out what's going wrong with the installation myself. I would appreciate any help you might be able to offer.

**Comment by hmcgaughey** [comment]
To anyone who has a similar problem, I have found the solution with help from Chat GPT. It appears that when I tried to install the neologd dictionary on my Mac using Terminal, I was missing some important software. As you can see in the above install script, there was an error in the final line:

`[install-mecab-ipadic-NEologd] : unxz is not found.`

To remedy that error, I had to install both Homebrew, a package manager for macOS, and the `unxz` compression tool. To do so, I used the following commands:

`$ /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"`
`$ (echo; echo 'eval "$(/opt/homebrew/bin/brew shellenv)"') >> /Users/hannamcgaughey/.zprofile`
`$ eval "$(/opt/homebrew/bin/brew shellenv)"`

The first command installs Homebrew and the second and third added it to my PATH, which is a list of directories that my Mac searches when I run a command. Adding Homebrew to my PATH allows me to easily run Homebrew commands from anywhere on my Mac and appears to be necessary to successfully run `unxz` in the installation of neologd.

The next step, then, is to install `unxz` using the following command:

`$ brew install xz`

Finally, it's possible to install neologd using the following commands:

`$ cd ~/mecab-ipadic-neologd`
`$ sudo ./bin/install-mecab-ipadic-neologd`

The first command navigates into the cloned file and the second completes the install. It's necessary to use `sudo` to run the installation script as an administrator, since it needs to write files to the /usr/local/lib/mecab/dic/ directory.

Thereafter I was able to successfully set the dictionary of mecab to neologd and parse the example sentence from the README file.

`$ mecab -d /usr/local/lib/mecab/dic/mecab-ipadic-neologd/`
`$ 8月3日に放送された「中居正広の金曜日のスマイルたちへ」(TBS系)で、1日たった5分でぽっこりおなかを解消す るというダイエット方法を紹介。キンタロー。のダイエットにも密着。`

The second command above was in the mecab software after I had already designated the neologd dictionary, and therefore I only needed to enter the sentence. The following command from the README file opens mecab, gives it the sentence, and designates the neologd dictionary all in one:

`$ echo "8月3日に放送された「中居正広の金曜日のスマイルたちへ」(TBS系)で、1日たった5分でぽっこりおなかを解消するというダイエット方法を紹介。キンタロー。のダイエットにも密着。" | mecab -d /usr/local/lib/mecab/dic/mecab`

On to the next, exciting steps into natural language processing for Japanese!
