### ISSUE TITLE
hatena keyword doesn't have 16 or higher yomigana characters.

### ISSUE THREAD

**Issue by ghost** [neologd/mecab-ipadic-neologd#9]
hatena keyword doesn't have 16 or higher yomigana characters.

e.g.
- うごめもしゅうへんのはてなでのも うごメモ周辺のはてなでの問題
- おしえてはてなだいありーでんごん 教えてはてなダイアリー伝言板
- しんはてなだいあらーえいがひゃく 真・はてなダイアラー映画百選

hatena keyword has proper yomigana when the yomigana has 15 or lower characters.

**Comment by neologd** [comment]
Thank you for your issue.

I don't think "Max yomigana length problem" is our problem to be solved.
And current max yomigana length of Hatena Keyword is 32.
Of course, I know the length was 16 before.

Even if there is just partial yomigana string, I think the yomigana string has a limited value.

I'm developing new system to solve this problem fundamentally.
Therefore I close this issue.

Stay tuned for new system :)
